version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "juornal"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"